### ISSUE TITLE
OverflowException when reporting coverage

### ISSUE THREAD

**Issue by mrfyda** [codacy/csharp-codacy-coverage#5]
User getting OverflowException when uploading the report:

<img width="736" alt="Screenshot 2019-10-25 at 15 29 07" src="https://user-images.githubusercontent.com/593860/67579395-4ccb4880-f73c-11e9-879d-082a72516dfb.png">
<br><br><i>(related to <a href='https://codacy.zendesk.com/agent/tickets/8221'>Zendesk ticket #8221</a>)<br>gz#8221</i>

**Comment by kreghek** [comment]
`--ReportType = DetailedXML` and the new version 1.0.3 helped. Thank!

**Comment by ajaymgaikwad** [comment]
Same error still we getting while upload code coverage report.

**Comment by ajaymgaikwad** [comment]
Hi @ljmf00 ,

We are using Resharper dotCover to generate code coverage, find attached Resharper version details for your reference. 
![cover_version](https://user-images.githubusercontent.com/51998124/68454356-58c80780-021e-11ea-988a-e5be7031892b.png)

**Comment by ljmf00** [comment]
Hi @ajaymgaikwad ,

Thanks for the additional information. If you are using `dotcover` you should specify `-e dotcover` instead of `-e opencover`.

Also, I was asking about **codacy** tool. If you are generating the report with `--ReportType=DetailedXML` you shouldn't have problems, because codacy need to know the file indices.

To avoid OverflowException, make sure you are using the latest version of the tool, its fixed with #6 PR.

Thanks,
Luis
